//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountBook
    {
        public System.Guid Id { get; set; }
        public int Categoryyy { get; set; }
        public int Amounttt { get; set; }
        public System.DateTime Dateee { get; set; }
        public string Remarkkk { get; set; }
    }
}
